openapi: 3.0.3
info:
  title: vat-validation
  version: '1.0.0'
paths:
  "/api/vies/check":
    post:
      operationId: vatCheck
      tags:
        - vatCheck
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/vatCheckRequest"
      responses:
        '200':
          description: "Request successfully processed. The response contains the result of the VAT number verification."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/vatCheckResponse"
        '400':
          description: "Invalid input parameters. Ensure that all required data is correctly provided and properly formatted."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/system"
        '500':
          description: "Internal server error. An unexpected issue occurred while processing the request."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/system"
        '503':
          description: "VIES service temporarily unavailable. The VAT number verification could not be completed at this time."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/system"
  "/api/vies/status":
    get:
      operationId: viesStatus
      tags:
        - viesStatus
      responses:
        '200':
          description: "Service is operational. The response provides the current status of the VIES service."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/viesStatusResponse"
        '503':
          description: "VIES service is currently unavailable. Unable to retrieve service status at this time."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/system"
  "/api/cache/clear":
    delete:
      operationId: clearCache
      tags:
        - clearCache
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/clearCacheRequest"
      responses:
        '200':
          description: "Cache successfully cleared."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/clearCacheResponse"
        '400':
          description: "Invalid input parameters. Verify the request body and ensure it follows the expected format."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/clearCacheResponse"
        '500':
          description: "Internal server error. An unexpected issue occurred while attempting to clear the cache."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/clearCacheResponse"
components:
  schemas:
    clearCacheRequest:
      type: object
      properties:
        keys:
          type: array
          description: "List of cache keys to be cleared"
          items:
            $ref: "#/components/schemas/key"
    key:
      type: object
      properties:
        iso2:
          type: string
          maxLength: 2
          minLength: 2
          description: "Country ISO 2"
        vatNumber:
          type: string
          description: "VAT number"
    vatCheckRequest:
      type: object
      required:
        - iso2
        - vatNumber
      properties:
        iso2:
          type: string
          maxLength: 2
          minLength: 2
          description: "Country ISO 2"
        vatNumber:
          type: string
          description: "VAT number"
    vatCheckResponse:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/vatCheckOutputData"
        system:
          $ref: "#/components/schemas/system"
    vatCheckOutputData:
      type: object
      properties:
        iso2:
          type: string
          description: "Country ISO 2"
        vatNumber:
          type: string
          description: "VAT number"
        valid:
          type: boolean
          description: "VAT number validity"
        name:
          type: string
          description: "Name of the VAT number holder"
        address:
          type: string
          description: "Address of the VAT number holder"
    clearCacheResponse:
      type: object
      properties:
        status:
          type: string
          enum: [ success, error ]
          description: "Operation status: 'success' if the cache was cleared, 'error' otherwise"
        message:
          type: string
          enum: [ Cache cleared successfully, Incorrect input parameters ]
          description: "Result description"
    viesStatusResponse:
      type: object
      properties:
        data:
          type: array
          description: "List of countries with VIES service status"
          items:
            $ref: "#/components/schemas/isoAvailable"
        system:
          $ref: "#/components/schemas/system"
    isoAvailable:
      type: object
      properties:
        iso2:
          type: string
          description: "Country ISO 2"
        status:
          type: string
          description: "Current status of the VIES service for the country"
    system:
      type: object
      properties:
        code:
          type: integer
          enum: [ 0, 1 ]
          x-enum-varnames:
            - OK
            - KO
          description: "System response code: 0 = OK, 1 = Error"
        description:
          type: string
          enum: [ Ok, Request to VIES failed, Error creating body of VIES service request, Error reading VIES response, Request body not valid ]
          description: "System description"